action_id: trunk-upgrade-available
date: 2023-11-16 00:26:36
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 2816
  out: ""
  err: ""
timestamp: 1700094396
full_timestamp:
  nanos: 589538000
  seconds: 1700094396
trunk_version: 1.17.2
